<?php

use Illuminate\Database\Seeder;

class ClienteTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('clients')->insert([
		'id'=>'1',
		'id_user'=>'3',
		'logo'=>'https://s-media-cache-ak0.pinimg.com/736x/33/b8/69/33b869f90619e81763dbf1fccc896d8d--lion-logo-modern-logo.jpg',
		'web'=>'www.weblogo.com',
		'link_web'=>'www.weblogo.com',
		'description'=>'description',
		'status'=>'1',
		]);
		DB::table('clients')->insert([
		'id'=>'2',
		'id_user'=>'3',
		'logo'=>'https://s-media-cache-ak0.pinimg.com/736x/33/b8/69/33b869f90619e81763dbf1fccc896d8d--lion-logo-modern-logo.jpg',
		'web'=>'www.weblogo.com',
		'link_web'=>'www.weblogo.com',
		'description'=>'description',
		'status'=>'1',
		]);
		DB::table('clients')->insert([
		'id'=>'3',
		'id_user'=>'3',
		'logo'=>'https://s-media-cache-ak0.pinimg.com/736x/33/b8/69/33b869f90619e81763dbf1fccc896d8d--lion-logo-modern-logo.jpg',
		'web'=>'www.weblogo.com',
		'link_web'=>'www.weblogo.com',
		'description'=>'description',
		'status'=>'1',
		]);
		DB::table('clients')->insert([
		'id'=>'4',
		'id_user'=>'3',
		'logo'=>'https://s-media-cache-ak0.pinimg.com/736x/33/b8/69/33b869f90619e81763dbf1fccc896d8d--lion-logo-modern-logo.jpg',
		'web'=>'www.weblogo.com',
		'link_web'=>'www.weblogo.com',
		'description'=>'description',
		'status'=>'1',
		]);
		DB::table('clients')->insert([
		'id'=>'5',
		'id_user'=>'3',
		'logo'=>'https://s-media-cache-ak0.pinimg.com/736x/33/b8/69/33b869f90619e81763dbf1fccc896d8d--lion-logo-modern-logo.jpg',
		'web'=>'www.weblogo.com',
		'link_web'=>'www.weblogo.com',
		'description'=>'description',
		'status'=>'1',
		]);
		DB::table('clients')->insert([
		'id'=>'6',
		'id_user'=>'3',
		'logo'=>'https://s-media-cache-ak0.pinimg.com/736x/33/b8/69/33b869f90619e81763dbf1fccc896d8d--lion-logo-modern-logo.jpg',
		'web'=>'www.weblogo.com',
		'link_web'=>'www.weblogo.com',
		'description'=>'description',
		'status'=>'1',
		]);
		DB::table('clients')->insert([
		'id'=>'7',
		'id_user'=>'3',
		'logo'=>'https://s-media-cache-ak0.pinimg.com/736x/33/b8/69/33b869f90619e81763dbf1fccc896d8d--lion-logo-modern-logo.jpg',
		'web'=>'www.weblogo.com',
		'link_web'=>'www.weblogo.com',
		'description'=>'description',
		'status'=>'1',
		]);
		DB::table('clients')->insert([
		'id'=>'8',
		'id_user'=>'3',
		'logo'=>'https://s-media-cache-ak0.pinimg.com/736x/33/b8/69/33b869f90619e81763dbf1fccc896d8d--lion-logo-modern-logo.jpg',
		'web'=>'www.weblogo.com',
		'link_web'=>'www.weblogo.com',
		'description'=>'description',
		'status'=>'1',
		]);
		DB::table('clients')->insert([
		'id'=>'9',
		'id_user'=>'3',
		'logo'=>'https://s-media-cache-ak0.pinimg.com/736x/33/b8/69/33b869f90619e81763dbf1fccc896d8d--lion-logo-modern-logo.jpg',
		'web'=>'www.weblogo.com',
		'link_web'=>'www.weblogo.com',
		'description'=>'description',
		'status'=>'1',
		]);
		DB::table('clients')->insert([
		'id'=>'10',
		'id_user'=>'3',
		'logo'=>'https://s-media-cache-ak0.pinimg.com/736x/33/b8/69/33b869f90619e81763dbf1fccc896d8d--lion-logo-modern-logo.jpg',
		'web'=>'www.weblogo.com',
		'link_web'=>'www.weblogo.com',
		'description'=>'description',
		'status'=>'1',
		]);
    }
}
